### ISSUE TITLE
Scenario config

### ISSUE THREAD

**Issue by elcuervo** [elcuervo/gerbil#7]
Instead of having a third argument during scenario creation a 'config' keyword should be added.

``` javascript
scenario('test', {
  'config': function(c) {
    c.formatter = prettyFormatter;
    c.finish = function(results) {
      // results => {passed: 1, failed: 2, pending: 3, assertions: 10}
    };
  },
});
```

Also a Gerbil.finish should be added to be executed in every test finish.

**Comment by pdjota** [comment]
What about:
results: {
  passed: {1, [list of tests]}. failed: { 2, [list of failed tests]} ...
}

List of failed tests:
"test desc.  line LIX"

**Comment by elcuervo** [comment]
The idea is not to overwrite the formatter, just to be able to trigger things when something fails, like re-run tests, or trigger mail notifications

**Comment by foca** [comment]
+1
